Update 0-custom_http_response_header

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,84 +1,49 @@
 #!/usr/bin/env bash
-# duplicate web-01 to web-02
-# these scripts are an upgrade from the web-server scripts...
-
-# uncomment to see the script run in action
-#set -x
-
-echo -e "Updating and doing some minor checks...\n"
-
-function install() {
-	command -v "$1" &> /dev/null
-
-	#shellcheck disable=SC2181
-	if [ $? -ne 0 ]; then
-		echo -e "	Installing: $1$\n"
-		sudo apt-get update -y -qq && \
-			sudo apt-get install -y "$1" -qq
-		echo -e "\n"
-	else
-		echo -e "	${1} is already installed.\n"
-	fi
-}
-
-install nginx #install nginx
-
-echo -e "\nSetting up some minor stuff.\n"
-
-# allowing nginx on firewall
+# to configure web-02 to be identical to web-01.
+# shellcheck disable=SC2154
+config_file="/etc/nginx/sites-available/default"
+name=$(hostname)
+sudo apt-get -y update
+sudo apt-get -y install nginx
+sudo service nginx start
+sudo chown -R "$USER":"$USER" /var/www/html
+sudo chmod -R 755 /var/www
+sudo rm /var/www/html/index.nginx-debian.html
+echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
+echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
 sudo ufw allow 'Nginx HTTP'
+# Check if the location block already exists
+if ! grep -q "error_page 404 /error_404.html;" "$config_file"; then
+    new_string=$(cat <<-EOL
+        server_name _;
 
-# Give the user ownership to website files for easy editing
-if [ -d "/var/www" ]; then
-	sudo chown -R "$USER":"$USER" /var/www
-	sudo chmod -R 755 /var/www
-else
-	sudo mkdir -p /var/www
-	sudo chown -R "$USER":"$USER" /var/www
-	sudo chmod -R 755 /var/www
+        error_page 404 /error_404.html;
+
+        location /redirect_me {
+            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
+        }
+EOL
+    )
+
+    # Use awk to replace the "server_name _;" line with the new configuration block
+    awk -v new_string="$new_string" '/server_name _;/ { print new_string; next }1' "$config_file" > "$config_file.tmp"
+
+    # Replace the original configuration file with the temporary file
+    sudo mv "$config_file.tmp" "$config_file"
 fi
+# adding x-serverd-by header
+# Check if the location block already exists
+if ! grep -q "add_header X-Served-By" "$config_file"; then
+    new_string=$(cat <<-EOL
+\t\t# as directory, then fall back to displaying a 404.
+\t\tadd_header X-Served-By "$name";
+EOL
+    )
 
-# create directories if not present
-for dir in /var/www/{html,error}; do
-	if ! [ -d "$dir" ]; then
-		mkdir -p "$dir"
-	fi
-done
+    # Use awk to replace the "server_name _;" line with the new configuration block
+    awk -v new_string="$new_string" '/# as directory, then fall back to displaying a 404./ { print new_string; next }1' "$config_file" > "$config_file.tmp"
 
-# creating new index
-echo "Hello World!" > /var/www/html/index.html
-
-# create new error page
-echo "Ceci n'est pas une page" > /var/www/html/error_404.html
-
-# backup default server config file
-sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
-
-server_config=\
-"server {
-		listen 80 default_server;
-		listen [::]:80 default_server;
-		root /var/www/html;
-		index index.html index.htm index.nginx-debian.html
-		server_name_;
-		add_header X-Served-By \$hostname;
-		location / {
-			try_files \$uri \$uri/ =404;
-		}
-		if (\$request_filename ~ redirect_me){
-			rewrite ^ https://th3-gr00t.tk/ permanent;
-		}
-		error_page 404 /error_404.html;
-		location = /error_404.html {
-			internal;
-		}
-}"
-
-#shellcheck disable=SC2154
-echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
-
-if [ "$(pgrep -c nginx)" -le 0 ]; then
-	sudo service nginx start
-else
-	sudo service nginx restart
+    # Replace the original configuration file with the temporary file
+    sudo mv "$config_file.tmp" "$config_file"
 fi
+sudo service nginx restart
